Update 3 example descriptions to newer format
auto-wcag/auto-wcag pull request #1560
Opened 2021-03-19 16:43 UTC by EmmaJP

Minor updates to 3 of the example descriptions to the newer format requirements, in https://act-rules.github.io/rules/6a7281 - ARIA state or property has valid value. 

Need for Final Call:
- no need for final call.

---

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Final Call period. In case of disagreement, the longer period wins.

2021-03-19 16:57 UTC, EmmaJP commented
@WilcoFiers Mira and I didn't go further because I didn't know if Passed Example 4 needed an element with the referenced id in the associated code snippet. Potentially a change that might need a final call, so not sure how you want to proceed.

Also, I don't know Mira's github id to assign the PR to her.

2021-04-01 09:49 UTC, ajanec01 approved these changes, later dismissed

2021-04-08 11:16 UTC, Jym77 requested changes, later dismissed
I'm not sure about the change from "property/state" to "attribute". This difference does exist in ARIA, so the terms are a bit more precise than just "attribute". Not a blocker, however.

2021-04-08 11:16 UTC, Jym77 commented on _rules/aria-state-or-property-valid-value-6a7281.md
> +This `aria-pressed` attribute has a valid true/false/mixed/undefined value.
```suggestion
This `aria-pressed` attribute has a valid tristate value.
```
"tristate" is the correct ARIA term for this attribute: https://www.w3.org/TR/wai-aria-1.2/#aria-pressed

2022-03-24 14:11 UTC, Jym77 approved these changes
We may want to link the value types to [their definitions](https://www.w3.org/TR/wai-aria-1.2/#propcharacteristic_value).

Not sure about it though (the same way we don't link element's or attribute's name to their HTML def).

2022-03-24 14:11 UTC, Jym77 commented on _rules/aria-state-or-property-valid-value-6a7281.md
> +This `aria-required` property has a valid true/false value.
```suggestion
This `aria-required` property has a valid [true/false](https://www.w3.org/TR/wai-aria-1.2/#valuetype_true-false) value.
```

2022-03-29 08:50 UTC, WilcoFiers approved these changes

2023-04-13 14:14 UTC, colabottles approved these changes

2023-08-31 14:53 UTC, WilcoFiers commented
This PR is completely out of date. All tests have since been rewritten.

2023-08-31 14:53 UTC, closed without merging