Update image-no-text-0va7u6.md
auto-wcag/auto-wcag pull request #1873
Opened 2022-06-21 16:48 UTC by ChrisLoiselle

Per discussion on 6/16/2022 call with AGWG ACT Task Force to update HTML graphics contain no text rule link wording.

<< Describe the changes >>

Closes issue(s):

- closes #XXX (ADD ISSUE NUMBER HERE)

Need for Call for Review:
<< choose one of the following and remove the rest >>
<< check [Process Document on Call for Review](https://act-rules.github.io/pages/design/process/#call-for-review) >>
This can be merged with 1 approval << choose reason: editorial changes to website/test code, adding new contributor, other (explain). >>
This will not require a Call for Review << choose reason(s): editorial changes (including to the applicability, expectation or examples section), changes to assumptions, background, accessibility support, change to website/test code (not rule), other (explain). >>
This will require a 1 week Call for Review << small changes affecting a small number of test cases, if in doubt do not use this. >>
This will require a 2 weeks Call for Review << new rule, or substantial changes affecting a large number of test cases, if in doubt, use this. >>

---

## Pull Request Etiquette

### **When creating PR:**

- [ ] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).
- [ ] Make sure you do not remove the "How to Review and Approve" section in your pull request description

### **After creating PR:**

- [ ] Add yourself (and co-authors) as "Assignees" for PR.
- [ ] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [ ] [Link the PR to any issue it solves](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). This will be done automatically by [referencing the issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) at the top of this comment in the indicated place.
- [ ] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

### **When merging a PR:**

- [ ] Close any issue that the PR resolves. This will happen automatically upon merging if the PR was correctly linked to the issue, e.g. by referencing the issue at the top of this comment.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

2022-06-21 16:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/act-rules/act-rules.github.io?pullRequest=1873) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/act-rules/act-rules.github.io?pullRequest=1873) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/act-rules/act-rules.github.io?pullRequest=1873) it.</sub>

2022-06-23 12:16 UTC, Jym77 submitted a review, later dismissed

2022-07-05 12:29 UTC, ChrisLoiselle commented on _rules/image-no-text-0va7u6.md
>  - **decoration**: the [embedded image][] the test target belongs to is [purely decorative][].
Hi @Jym77 ,

Could you confirm you are ok with:

For each test target, its [visible pixels][visible] do not contain text expressing anything in a [human language], except if at least one of the following is true:
- **essential**: the [visible pixels][visible] of the test target contain text for which its presentation is [essential][]; or
- **significant**: the [visible pixels][visible] of the test target contain text and the text is not a significant part of the visible part of the image or
- **decoration**: the [embedded image][] the test target belongs to is [purely decorative][].

If so, I'll update the pull request . Thanks ! Chris

2022-07-05 12:40 UTC, Jym77 commented on _rules/image-no-text-0va7u6.md
>  - **decoration**: the [embedded image][] the test target belongs to is [purely decorative][].
Yes, that looks good 👍

2022-07-12 14:16 UTC, HelenBurge approved these changes

2022-07-14 08:53 UTC, Jym77 requested changes, later dismissed

2022-07-14 08:53 UTC, Jym77 commented on _rules/image-no-text-0va7u6.md
> +## Expectations
```suggestion
## Expectation
```

2022-07-14 08:53 UTC, Jym77 commented on _rules/image-no-text-0va7u6.md
> +## Exceptions
```suggestion
```

2022-07-26 19:59 UTC, wcreedle approved these changes

2022-07-29 19:06 UTC, wcreedle approved these changes

2022-08-02 21:34 UTC, kengdoj commented on _rules/image-no-text-0va7u6.md
> +- **significant**: the [visible pixels][visible] of the test target contain text and the text is not a significant part of the visible part of the image or
```suggestion
- **not significant**: the [visible pixels][visible] of the test target contain text and the text is not a significant part of the visible part of the image or
```

2022-08-02 21:37 UTC, kengdoj commented on _rules/image-no-text-0va7u6.md
>  - **decoration**: the [embedded image][] the test target belongs to is [purely decorative][].
```suggestion
- **decoration**: the test target belongs to an [embedded image][] that is [purely decorative][].
```

2022-08-03 20:55 UTC, wcreedle submitted a review, later dismissed

2022-08-03 22:58 UTC, kengdoj approved these changes

2022-08-09 13:56 UTC, wcreedle approved these changes

2022-08-22 13:27 UTC, WilcoFiers commented on _rules/image-no-text-0va7u6.md
>  - **essential**: the [visible pixels][visible] of the test target contain text for which its presentation is [essential][]; or
I'm not so sure we should use "essential" here. It's sort of out of scope of this PR, but it's very relevant in moving this rule forward. We had a discussion about "essential" last week in ACT TF and our impression there was that it was too ambiguous to be used in an expectation.

2022-09-01 13:12 UTC, ChrisLoiselle commented on _rules/image-no-text-0va7u6.md
>  - **essential**: the [visible pixels][visible] of the test target contain text for which its presentation is [essential][]; or
Hi @WilcoFiers , your points seem to point at both including and excluding it. I'm happy to have a discussion to decide on what we are doing within the most recent submission for updates.

2022-09-06 14:10 UTC, WilcoFiers approved these changes

2022-09-06 14:10 UTC, WilcoFiers commented on _rules/image-no-text-0va7u6.md
>  - **essential**: the [visible pixels][visible] of the test target contain text for which its presentation is [essential][]; or
I'll open an issue. This is not related to your PR. Feel free to move forward with that.

2022-09-08 12:44 UTC, ChrisLoiselle commented on _rules/image-no-text-0va7u6.md
>  - **essential**: the [visible pixels][visible] of the test target contain text for which its presentation is [essential][]; or
So I can resolve this conversation ? I see https://github.com/act-rules/act-rules.github.io/issues/1915 however not sure what to do with https://github.com/act-rules/act-rules.github.io/pull/1873 currently.

2022-09-22 14:05 UTC, merged