meta-refresh editorial tweak
auto-wcag/auto-wcag pull request #1908
Opened 2022-08-05 09:02 UTC by WilcoFiers

Change "SC 2.2.1" to "2.2.1 Time Adjustable", and add a link

Need for Call for Review: none, editorial

---

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

2022-08-05 09:57 UTC, Jym77 requested changes, later dismissed

2022-08-05 09:57 UTC, Jym77 commented on _rules/meta-refresh-no-delay-bc659a.md
> +- This rule assumes that the refresh was not [essential](https://www.w3.org/TR/WCAG21/#dfn-essential), which is listed as a valid exception to [2.2.1 Time Adjustable][sc211].
```suggestion
- This rule assumes that the refresh was not [essential](https://www.w3.org/TR/WCAG21/#dfn-essential), which is listed as a valid exception to [2.2.1 Time Adjustable][sc221].
```

2022-08-05 10:53 UTC, carlosapaduarte approved these changes

2022-08-05 10:58 UTC, Jym77 approved these changes

2022-08-05 13:34 UTC, HelenBurge approved these changes

2022-08-08 20:38 UTC, kengdoj approved these changes

2022-08-10 17:57 UTC, kengdoj approved these changes

2022-08-12 16:57 UTC, merged