aria-hidden not focusable, add hidden svg in link example
auto-wcag/auto-wcag pull request #1933
Opened 2022-10-04 10:56 UTC by WilcoFiers

Request from AGWG to add an example showing aria-hidden used on an SVG that is inside a link.

Need for Call for Review: 1 week

---

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

2022-10-06 14:42 UTC, colabottles approved these changes

2022-10-07 08:16 UTC, Jym77 requested changes, later dismissed

2022-10-07 08:16 UTC, Jym77 commented on _rules/aria-hidden-no-focusable-content-6cfa84.md
> +This `svg` element with `aria-hidden` is a descendant of a focusable link, rather than an ancestor.
```suggestion
This `svg` element with `aria-hidden` does not have a focusable descendant, focusable ancestors are not a problem for this rule.
```
I usually prefer description that follow the wording of expectation.

2022-10-07 09:19 UTC, Jym77 approved these changes

2022-10-07 14:40 UTC, carlosapaduarte approved these changes

2022-10-21 11:46 UTC, merged