Create manual_test_rule_template
auto-wcag/auto-wcag pull request #1979
Opened 2022-11-24 14:59 UTC by HelenBurge

Adding a first go at the manual test rule template (same as the others but with extra guidance at the start)

Starting on the work for the new manual test rules 

Closes issue(s):

Need for Call for Review:
This will not require a Call for Review - it is a template

---

## Pull Request Etiquette

### **When creating PR:**

- [ ] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).
- [ ] Make sure you do not remove the "How to Review and Approve" section in your pull request description

### **After creating PR:**

- [ ] Add yourself (and co-authors) as "Assignees" for PR.
- [ ] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [ ] [Link the PR to any issue it solves](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). This will be done automatically by [referencing the issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) at the top of this comment in the indicated place.
- [ ] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

### **When merging a PR:**

- [ ] Close any issue that the PR resolves. This will happen automatically upon merging if the PR was correctly linked to the issue, e.g. by referencing the issue at the top of this comment.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

2022-12-01 12:17 UTC, WilcoFiers approved these changes

2022-12-01 12:46 UTC, Jym77 approved these changes
The file should be moved together with the other templates.

2023-01-02 17:36 UTC, carlosapaduarte approved these changes
With a small suggestion. Feel free to leave it out.

2023-01-02 17:36 UTC, carlosapaduarte commented on manual_test_rule_template
> +This is the template for the manual test rules. It matches the automation rules but there are parts that can be completed with help (like adding examples of code).
```suggestion
This is the template for the manual test rules. It matches the automation rules but there are parts that can be completed with help from other community members (like adding examples of code).
```

2023-01-05 11:57 UTC, Jym77 commented
There is a problem with the tests 🙈 
Due to the text at the start, before the first `---`, the frontmatter is not seen by the parsing (`.use(remarkFrontmatter)` in `getMarkdownData`). In turn, this means that
* `prettier` tries to re-pretties it and break the correct indentation it should have (mildly annoying).
* spell check tries to spell-check the frontmatter and complains about `forConformance` or similar keys (very annoying since it breaks tests and we cannot merge).

Easy solutions:
* Move instructions inside (or after) the frontmatter. This may be a bit more annoying for rule writers, but would solve both problems.
* Add spelling exceptions. A bit dirty but working to solve the second problem. The first stays.
* Ignore this file in `describe-page.js` and in the prettier hook. Could also work; not sure how to ignore it in the prettier hook, though.

@HelenBurge Do you think that moving the instructions inside, or after the frontmatter (after the first or second `---`) would be OK? Essentially, there cannot be anything before the first `---` in the file.

2023-01-05 13:28 UTC, HelenBurge commented
> There is a problem with the tests 🙈 Due to the text at the start, before the first `---`, the frontmatter is not seen by the parsing (`.use(remarkFrontmatter)` in `getMarkdownData`). In turn, this means that
> 
> * `prettier` tries to re-pretties it and break the correct indentation it should have (mildly annoying).
> * spell check tries to spell-check the frontmatter and complains about `forConformance` or similar keys (very annoying since it breaks tests and we cannot merge).
> 
> Easy solutions:
> 
> * Move instructions inside (or after) the frontmatter. This may be a bit more annoying for rule writers, but would solve both problems.
> * Add spelling exceptions. A bit dirty but working to solve the second problem. The first stays.
> * Ignore this file in `describe-page.js` and in the prettier hook. Could also work; not sure how to ignore it in the prettier hook, though.
> 
> @HelenBurge Do you think that moving the instructions inside, or after the frontmatter (after the first or second `---`) would be OK? Essentially, there cannot be anything before the first `---` in the file.

I have amended the instructions to be after the ---

2023-01-05 13:36 UTC, Jym77 commented on pages/design/manual-template-empty.md
> +For the starting section, and examples, complete what you feel comfortable with and then ask for help via emails to the chairs of the ACT Task Force and Community Group. Delete these instructions aft
```suggestion
For the starting section, and examples, complete what you feel comfortable with and then ask for help via emails to the chairs of the ACT Task Force and Community Group. Delete these instructions after the --- and before "## Applicability" (delete rows 38-42).
```

2023-01-06 19:14 UTC, carlosapaduarte requested changes
Changes proposed by Jean-Yves need to be applied

2023-01-20 19:12 UTC, carlosapaduarte approved these changes

2023-01-24 11:52 UTC, WilcoFiers approved these changes

2023-01-31 10:18 UTC, merged