Adding wording which explains the difference between the same context and identical contexts.
auto-wcag/auto-wcag pull request #1981
Opened 2022-11-30 01:56 UTC by dan-tripp-siteimprove

For rule fd3a94 (Links with identical accessible names and same context serve equivalent purpose): Adding wording which explains the difference between the same context and identical contexts.

Closes issue(s):

- none

Need for Call for Review:
This can be merged with 1 approval << choose reason: editorial changes to website/test code, adding new contributor, other (explain). 
** This PR only changes wording, and (I hope) adds clarity.  It doesn't change any meaning.
---

## Pull Request Etiquette

### **When creating PR:**

- [ ] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).
- [ ] Make sure you do not remove the "How to Review and Approve" section in your pull request description

### **After creating PR:**

- [ ] Add yourself (and co-authors) as "Assignees" for PR.
- [ ] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [ ] [Link the PR to any issue it solves](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). This will be done automatically by [referencing the issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) at the top of this comment in the indicated place.
- [ ] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

### **When merging a PR:**

- [ ] Close any issue that the PR resolves. This will happen automatically upon merging if the PR was correctly linked to the issue, e.g. by referencing the issue at the top of this comment.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

2022-11-30 01:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/act-rules/act-rules.github.io?pullRequest=1981) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/act-rules/act-rules.github.io?pullRequest=1981) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/act-rules/act-rules.github.io?pullRequest=1981) it.</sub>

2022-12-01 12:19 UTC, WilcoFiers approved these changes

2022-12-01 12:48 UTC, Jym77 approved these changes

2023-01-02 17:33 UTC, carlosapaduarte requested changes
Clearing up whitespace and suggest the removal of a sentence

2023-01-02 17:33 UTC, carlosapaduarte commented on _rules/links-with-identical-names-and-context-serve-equivalent-purpose-fd3a94.md
> +There is a difference between two contexts being the *same* and being *identical*.  This rule specifically targets links within the *same* context.  The same context means exactly the same set of DOM
```suggestion
There is a difference between two contexts being the *same* and being *identical*. This rule specifically targets links within the *same* context. The same context means exactly the same set of DOM nodes. Identical (but not the same) contexts might have a different set of DOM nodes, but those DOM nodes have equivalent content - such as text content, attribute values, and so on. This difference is similar to the difference in some programming languages between pointer equivalence and deep object equivalence. Links with identical name that are in identical (but not the same) contexts also fail [2.4.4 Link Purpose (In Context)][sc244]. However, defining "identical context" unambiguously has been deemed infeasible at this time, and so has been left out of this rule.
```

2023-01-02 17:33 UTC, carlosapaduarte commented on _rules/links-with-identical-names-and-context-serve-equivalent-purpose-fd3a94.md
> +There is a difference between two contexts being the *same* and being *identical*.  This rule specifically targets links within the *same* context.  The same context means exactly the same set of DOM
```suggestion
There is a difference between two contexts being the *same* and being *identical*.  This rule specifically targets links within the *same* context.  The same context means exactly the same set of DOM nodes.  Identical (but not the same) contexts might have a different set of DOM nodes, but those DOM nodes have equivalent content - such as text content, attribute values, and so on.  Links with identical name that are in identical (but not the same) contexts also fail [2.4.4 Link Purpose (In Context)][sc244]. However, defining "identical context" unambiguously has been deemed infeasible at this time, and so has been left out of this rule.
```

I don't think we need this sentence to explain the different between same and equivalent. But I won't block accepting the PR if you prefer to keep it.

2023-01-02 17:33 UTC, carlosapaduarte commented on _rules/links-with-identical-names-and-context-serve-equivalent-purpose-fd3a94.md
> +These two HTML `a` elements have the same [accessible name][] and link to the [same resource][] but different [programmatically determined link contexts][programmatically determined link context]. Ev
```suggestion
These two HTML `a` elements have the same [accessible name][] and link to the [same resource][] but different [programmatically determined link contexts][programmatically determined link context]. Even though the two contexts in this example are *identical*, they are not the *same*. That is: even though they have equivalent content, they do not consist of the same DOM elements.
```

2023-01-03 19:36 UTC, dan-tripp-siteimprove commented
> Clearing up whitespace and suggest the removal of a sentence

Your edits look good to me.  Thank you, Carlos.

2023-01-04 18:06 UTC, carlosapaduarte commented
@dan-tripp-siteimprove A quick follow-up on the use of GitHub for the reviewing process (this is something that happens often). Even tough you committed changes I proposed, you will notice that my review is still marked as "changes requested". After you address a review, you need to go to the widget at the end of the page (above the comments box) and expand the "1 change requested" details element. There you will find my review with an ellipsis symbol on the right. Press that and select "Dismiss review". Then you need to go to the top right side bar, and under reviews, re-request a review from me again.
Only after these steps, will GitHub allow me review again and Accept (or not, in case I do not agree with the way my review has been handled) your PR.

2023-01-04 18:07 UTC, carlosapaduarte approved these changes

2023-01-04 18:09 UTC, carlosapaduarte commented
> @dan-tripp-siteimprove A quick follow-up on the use of GitHub for the reviewing process (this is something that happens often). Even tough you committed changes I proposed, you will notice that my review is still marked as "changes requested". After you address a review, you need to go to the widget at the end of the page (above the comments box) and expand the "1 change requested" details element. There you will find my review with an ellipsis symbol on the right. Press that and select "Dismiss review". Then you need to go to the top right side bar, and under reviews, re-request a review from me again.
> Only after these steps, will GitHub allow me review again and Accept (or not, in case I do not agree with the way my review has been handled) your PR.

Apparently, my input was wrong :-) Even with the request for changes you were able to request my review, and I was able to complete it!

2023-01-04 22:13 UTC, dan-tripp-siteimprove commented
I accidentally clicked something yesterday - one of those "review" buttons, I forget which one. That might have caused some confusion.  At any rate - thank you.

2023-02-28 12:24 UTC, merged