"Iframe element has non-empty accessible name" [cae760]: use `tabindex`
auto-wcag/auto-wcag pull request #2019
Opened 2023-01-26 10:35 UTC by Jym77

Replace "can be accessed by sequential focus navigation" with "non-negative tabindex".
This align with the recent changes made in #1855 on the other rule with iframes and tabindexes.

Closes issue(s):

- closes #2015

Need for Call for Review:
This will require a 1 week Call for Review (aligning phrasing without changing intend)

---

## Pull Request Etiquette

### **When creating PR:**

- [X] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).
- [X] Make sure you do not remove the "How to Review and Approve" section in your pull request description

### **After creating PR:**

- [X] Add yourself (and co-authors) as "Assignees" for PR.
- [X] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [X] [Link the PR to any issue it solves](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). This will be done automatically by [referencing the issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) at the top of this comment in the indicated place.
- [X] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

### **When merging a PR:**

- [ ] Close any issue that the PR resolves. This will happen automatically upon merging if the PR was correctly linked to the issue, e.g. by referencing the issue at the top of this comment.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

2023-01-26 10:51 UTC, giacomo-petri requested changes

2023-01-26 10:51 UTC, giacomo-petri commented on _rules/iframe-non-empty-accessible-name-cae760.md
> +This rule applies to `iframe` elements that are [included in the accessibility tree][] and that do not have an negative `tabindex` [attribute value][].
```suggestion
This rule applies to `iframe` elements that are [included in the accessibility tree][] and that do not have a negative `tabindex` [attribute value][].
```

2023-01-26 10:51 UTC, giacomo-petri commented on _rules/iframe-non-empty-accessible-name-cae760.md
> +[attribute valiue]: #attribute-value 'Definition of Attribute value'
```suggestion
[attribute value]: #attribute-value 'Definition of Attribute value'
```

2023-01-26 15:17 UTC, HelenBurge approved these changes

2023-01-27 18:19 UTC, carlosapaduarte approved these changes

2023-01-27 18:35 UTC, ajanec01 commented on _rules/iframe-non-empty-accessible-name-cae760.md
> +This rule applies to `iframe` elements that are [included in the accessibility tree][] and that do not have a negative `tabindex` [attribute value][].
```suggestion
This rule applies to `iframe` elements that are [included in the accessibility tree][] and do not have a negative `tabindex` [attribute value][].
```
Maybe its me but it I find that to sound a bit better.

2023-01-30 07:58 UTC, giacomo-petri approved these changes

2023-01-31 12:05 UTC, ajanec01 approved these changes

2023-02-07 13:19 UTC, WilcoFiers approved these changes

2023-02-09 13:26 UTC, Jym77 commented
Call for review ends on February 16th.

2023-02-10 18:04 UTC, catdro approved these changes

2023-02-16 10:08 UTC, Jym77 commented
Call for review has ended. Merging.

2023-02-16 10:09 UTC, merged