Add 1.4.10 as a secondary S.C.
auto-wcag/auto-wcag pull request #2035
Opened 2023-02-20 22:40 UTC by sboptum

* added 1.4.10 as a secondary S.C. in the metadata
* added Understanding 1.4.10 in the Bibliography section

<< Describe the changes >>

Closes issue(s):

- closes #2025 

Need for Call for Review:
<< choose one of the following and remove the rest >>

This can be merged with 1 approval << choose reason: editorial changes to website/test code>>
---

## Pull Request Etiquette

### **When creating PR:**

- [ ] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).
- [ ] Make sure you do not remove the "How to Review and Approve" section in your pull request description

### **After creating PR:**

- [ ] Add yourself (and co-authors) as "Assignees" for PR.
- [ ] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [ ] [Link the PR to any issue it solves](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). This will be done automatically by [referencing the issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) at the top of this comment in the indicated place.
- [ ] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

### **When merging a PR:**

- [ ] Close any issue that the PR resolves. This will happen automatically upon merging if the PR was correctly linked to the issue, e.g. by referencing the issue at the top of this comment.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

2023-02-22 11:31 UTC, WilcoFiers approved these changes

2023-02-22 18:44 UTC, carlosapaduarte requested changes

2023-02-22 18:44 UTC, carlosapaduarte commented on _rules/meta-viewport-b4f0c3.md
> +    secondary: True
For coherence with other uses of Boolean values in the metadata

```suggestion
    secondary: true
```

2023-02-22 19:37 UTC, carlosapaduarte approved these changes

2023-02-23 10:00 UTC, Jym77 approved these changes

2023-02-24 18:40 UTC, carlosapaduarte commented
Merging

2023-02-24 18:41 UTC, merged