Fix typos in two examples
auto-wcag/auto-wcag pull request #2057
Opened 2023-04-25 11:42 UTC by WilcoFiers

Closes https://github.com/w3c/wcag-act-rules/issues/197

Need for Call for Review: none - these should not impact implementation

---

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

2023-04-25 13:17 UTC, daniel-montalvo approved these changes

2023-04-25 13:30 UTC, HelenBurge requested changes, later dismissed

2023-04-25 13:30 UTC, HelenBurge commented on _rules/aria-required-context-role-ff89c9.md
>  There is no element whose role has [required context role][] because the `header` role does not have one.
> There is no element whose role has [required context role][] because the `header` role does not have one.

"Header" should be amended here too?

2023-04-25 13:30 UTC, Jym77 approved these changes

2023-04-27 16:01 UTC, colabottles approved these changes

2023-05-11 11:52 UTC, WilcoFiers commented on _rules/aria-required-context-role-ff89c9.md
>  There is no element whose role has [required context role][] because the `header` role does not have one.
```suggestion
There is no element whose role has [required context role][] because the `heading` role does not have one.
```

2023-05-11 12:23 UTC, merged