UpdateTableHeaderRule
auto-wcag/auto-wcag pull request #2074
Opened 2023-06-20 09:30 UTC by HelenBurge

Adding the update from the Task force meeting (removing the use of role="row"): https://docs.google.com/spreadsheets/d/1OSkPFocXk4K3zYLnwS78WLsWO4PvE5yRcsauyefuIUI/edit#gid=1850701681

Closes issue(s):

Need for Call for Review:
This will require a 1 week Call for Review 
---

## Pull Request Etiquette

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

2023-06-22 12:15 UTC, Jym77 approved these changes

2023-06-22 13:05 UTC, WilcoFiers approved these changes

2023-06-26 17:42 UTC, 0066135 approved these changes

2023-06-29 09:59 UTC, Jym77 requested changes

2023-06-29 09:59 UTC, Jym77 commented on _rules/table-header-cell-has-assigned-cells-d0f69e.md
> +    - Helen Burge
```suggestion
    - Audrey Maniez
    - Helen Burge    
    - Jey Nandakumar
```
Should make the test happy (authors in alphabetical order)

2023-06-29 11:12 UTC, Jym77 approved these changes

2023-07-04 09:20 UTC, carlosapaduarte approved these changes

2023-07-14 11:01 UTC, merged