Deprecate HTML page lang and xml:lang attributes have matching values
auto-wcag/auto-wcag pull request #2086
Opened 2023-07-13 13:58 UTC by WilcoFiers

Modern assistive technologies do not use xml:lang when the lang attribute is used, regardless of how a page is served. There is no situation in which a difference between xml:lang and lang can cause an accessibility issue as far as any of us can tell. The lang attribute still has to be correct though.

Closes #1921

Need for Call for Review: 2 weeks, this is a substantial change

---

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

2023-07-13 15:12 UTC, carlosapaduarte requested changes, later dismissed
Just a single editorial

2023-07-13 15:12 UTC, carlosapaduarte commented on _rules/html-page-lang-xml-lang-match-5b7ae0.md
> +  This rule has been deprecated, as modern screen readers no longer use xml:lang when the lang attribute is given, regardless of which MIME type the pages is served with. This rule is not maintained
```suggestion
  This rule has been deprecated, as modern screen readers no longer use xml:lang when the lang attribute is given, regardless of which MIME type the page is served with. This rule is not maintained anymore and should not be used.
```

2023-07-14 11:43 UTC, carlosapaduarte approved these changes

2023-07-20 07:29 UTC, Jym77 approved these changes

2023-07-20 13:44 UTC, tbostic32 approved these changes

2023-07-20 13:47 UTC, kengdoj approved these changes

2023-07-20 18:30 UTC, 0066135 approved these changes

2023-07-20 21:09 UTC, colabottles approved these changes

2023-08-02 14:22 UTC, merged