Update element-lang-valid-de46e4.md
auto-wcag/auto-wcag pull request #2093
Opened 2023-07-26 23:34 UTC by kengdoj

Remove `<html>` and `<body>` tags from the displayed code examples so these don't cause unintended failures.

Closes #2091, which was identified during the annual re-review of this rule.  

`<html>` without a lang attribute would be a failure of an SC that this rule does not map to.

2023-07-27 13:05 UTC, colabottles approved these changes

2023-07-28 15:26 UTC, 0066135 approved these changes

2023-07-28 20:28 UTC, sujisreerama approved these changes

2023-08-01 13:39 UTC, WilcoFiers submitted a review, later dismissed
Also, would you mind putting in the description that this requires a 1 week call for review?

2023-08-01 13:39 UTC, WilcoFiers commented on _rules/element-lang-valid-de46e4.md
> +	</article>
```suggestion
<article lang="en">
	They wandered into a strange Tiki bar on the edge of the small beach town.
</article>
```

2023-08-01 13:39 UTC, WilcoFiers commented on _rules/element-lang-valid-de46e4.md
> +	</blockquote>
```suggestion
<blockquote lang="fr-CH">
	Ils ont trouvé un étrange bar Tiki aux abords de la petite ville balnéaire.
</blockquote>
```

2023-08-01 13:39 UTC, WilcoFiers commented on _rules/element-lang-valid-de46e4.md
> +	</p>
```suggestion
<p lang="en-US-GB">
	They wandered into a strange Tiki bar on the edge of the small beach town.
</p>
```

2023-08-01 13:39 UTC, WilcoFiers commented on _rules/element-lang-valid-de46e4.md
> +	</article>
```suggestion
<article lang="invalid">
	<div lang="en">
		They wandered into a strange Tiki bar on the edge of the small beach town.
	</div>
</article>
```

2023-08-01 13:39 UTC, WilcoFiers commented on _rules/element-lang-valid-de46e4.md
> +	</div>
```suggestion
<div lang="EN">
	<img src="/test-assets/shared/fireworks.jpg" alt="Fireworks over Paris" />
</div>
```

2023-08-01 13:39 UTC, WilcoFiers commented on _rules/element-lang-valid-de46e4.md
> +	</article>
```suggestion
<article lang="dutch">
	Zij liepen een vreemde Tiki bar binnen, aan de rand van een dorpje aan het strand.
</article>
```

2023-08-01 13:39 UTC, WilcoFiers commented on _rules/element-lang-valid-de46e4.md
> +	</article>
```suggestion
<article lang="#!">
	They wandered into a strange Tiki bar on the edge of the small beach town.
</article>
```

2023-08-01 13:39 UTC, WilcoFiers commented on _rules/element-lang-valid-de46e4.md
> +	</article>
```suggestion
<article lang="  ">
	They wandered into a strange Tiki bar on the edge of the small beach town.
</article>
```

2023-08-01 13:39 UTC, WilcoFiers commented on _rules/element-lang-valid-de46e4.md
> +	</article>
```suggestion
<article lang="english">
	<p aria-hidden="true">
		They wandered into a strange Tiki bar on the edge of the small beach town.
	</p>
</article>
```

2023-08-01 13:39 UTC, WilcoFiers commented on _rules/element-lang-valid-de46e4.md
> +	</article>
```suggestion
<article lang="English">
	<p style="position: absolute; top: -9999px">
		They wandered into a strange Tiki bar on the edge of the small beach town.
	</p>
</article>
```

2023-08-01 13:39 UTC, WilcoFiers commented on _rules/element-lang-valid-de46e4.md
> +	</article>
```suggestion
<article lang="en">
	<div lang="invalid">
		They wandered into a strange Tiki bar on the edge of the small beach town.
	</div>
</article>
```

2023-08-01 13:39 UTC, WilcoFiers commented on _rules/element-lang-valid-de46e4.md
> +	</div>
```suggestion
<div lang="invalid">
	<img src="/test-assets/shared/fireworks.jpg" alt="Fireworks over Paris" />
</div>
```

2023-08-01 13:39 UTC, WilcoFiers commented on _rules/element-lang-valid-de46e4.md
> +
```suggestion
<p lang="eng">I love ACT rules!</p>
```

2023-08-01 13:39 UTC, WilcoFiers commented on _rules/element-lang-valid-de46e4.md
> +	<p lang="i-lux">Lëtzebuerg ass e Land an Europa.</p>
```suggestion
<p lang="i-lux">Lëtzebuerg ass e Land an Europa.</p>
```

2023-08-01 13:39 UTC, WilcoFiers commented on _rules/element-lang-valid-de46e4.md
> +	They wandered into a strange Tiki bar on the edge of the small beach town.
How about we put an HTML element here still, just to show this is HTML?

```suggestion
<p>They wandered into a strange Tiki bar on the edge of the small beach town.</p>
```

2023-08-01 13:39 UTC, WilcoFiers commented on _rules/element-lang-valid-de46e4.md
> +	</article>
```suggestion
<article lang="">
	They wandered into a strange Tiki bar on the edge of the small beach town.
</article>
```

2023-08-01 13:39 UTC, WilcoFiers commented on _rules/element-lang-valid-de46e4.md
> +	</p>
```suggestion
<p lang="hidden">
	<span style="display: none;">
		They wandered into a strange Tiki bar on the edge of the small beach town.
	</span>
</p>
```

2023-08-01 13:39 UTC, WilcoFiers commented on _rules/element-lang-valid-de46e4.md
> +	</div>
```suggestion
<div lang="invalid">
	<img src="/test-assets/shared/fireworks.jpg" alt="" />
</div>
```

2023-08-01 13:39 UTC, WilcoFiers commented on _rules/element-lang-valid-de46e4.md
> +	<div lang="invalid"></div>
```suggestion
<div lang="invalid"></div>
```

2023-08-02 21:18 UTC, colabottles approved these changes

2023-08-03 19:44 UTC, tbostic32 approved these changes

2023-08-07 08:41 UTC, Jym77 requested changes
The problem  I see with this (and the reason these tags where here in the first place), is that the rule only apply to elements that are descendant of a `body` element.

I think we should keep the `body` element in the displayed examples fors this reason, otherwise they wouldn't correctly illustrate the rule.
It would be a better fix to add `lang="en"` to all the `html` elements, and keep the `body` elements.

2023-08-10 14:02 UTC, WilcoFiers commented
@Jym77 Thanks for sharing your thought. We talked about it in TF, and I ended up changing my mind on this and agreeing with you. We shouldn't rely on people knowing browser magic to understand the examples.

2023-08-10 14:09 UTC, colabottles reviewed
I am actually going to backtrack myself and agree with @Jym77 as well. I think we need to keep the `<body>` and `<html>` tags.

2023-08-10 14:24 UTC, kengdoj commented
Thanks, all. 

I'm going to close this PR and open a new one to make the updates as @Jym77 suggested.

2023-08-10 14:24 UTC, closed without merging