"Element with lang attribute has valid language tag" [de46e4]: Updated Failed Examples 4 and 5 to reflect Applicability
auto-wcag/auto-wcag pull request #2094
Opened 2023-07-27 09:59 UTC by giacomo-petri

I've updated:
- Failed Example 4 
- Failed Example 5

to reflect the updated Applicability, including a reference to the [text inheriting its programmatic language][] definition in each failure.

Closes issue(s): #2063

Need for Call for Review:
This will require a 1 week Call for Review 

---

## Pull Request Etiquette

### **When creating PR:**

- [ ] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).
- [ ] Make sure you do not remove the "How to Review and Approve" section in your pull request description

### **After creating PR:**

- [ ] Add yourself (and co-authors) as "Assignees" for PR.
- [ ] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [ ] [Link the PR to any issue it solves](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). This will be done automatically by [referencing the issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) at the top of this comment in the indicated place.
- [ ] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

### **When merging a PR:**

- [ ] Close any issue that the PR resolves. This will happen automatically upon merging if the PR was correctly linked to the issue, e.g. by referencing the issue at the top of this comment.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

2023-08-10 09:23 UTC, Jym77 requested changes
Minor polishing.

2023-08-10 09:23 UTC, Jym77 commented on _rules/element-lang-valid-de46e4.md
> +The `lang` [attribute value][] does not have a valid language tag. Even though its descendant `p` element is not [included in the accessibility tree][] due to the presence of the `aria-hidden="true"`
```suggestion
The `lang` [attribute value][] does not have a valid language tag. Even though the `p` element is not [included in the accessibility tree][] due to the presence of the `aria-hidden="true"` attribute, it is [visible][]; therefore its content is [text inheriting its programmatic language][] from the `article` element. Hence, the lang attribute must be valid.
```
(there is only one `p` element, so no need to disambiguate, plus "its (descendant)" refers here to the `lang` attribute (value) (subject of the previous sentence) making "its descendant" technically incorrect)

2023-08-10 09:23 UTC, Jym77 commented on _rules/element-lang-valid-de46e4.md
> +The `lang` [attribute value][] does not have a valid language tag. Even though its descendant `p` element is not [visible][] due to the CSS properties set, the content of the `p` element is still [te
```suggestion
The `lang` [attribute value][] does not have a valid language tag. Even though the `p` element is not [visible][] due to the being moved off-screen, it is [included in the accessibility tree][]; therefore its content is [text inheriting its programmatic language][] from the `article` element. Hence, the lang attribute must be valid.
```

2023-08-31 12:27 UTC, Jym77 submitted a review, later dismissed

2023-08-31 12:59 UTC, colabottles approved these changes

2023-09-05 20:56 UTC, dan-tripp-siteimprove requested changes

2023-09-05 20:56 UTC, dan-tripp-siteimprove commented on _rules/element-lang-valid-de46e4.md
> +The `lang` [attribute value][] does not have a valid language tag. Even though the `p` element is not [visible][] due to the being moved off-screen, it is [included in the accessibility tree][]; ther
```suggestion
The `lang` [attribute value][] does not have a valid language tag. Even though the `p` element is not [visible][] due to it being moved off-screen, it is [included in the accessibility tree][]; therefore its content is [text inheriting its programmatic language][] from the `article` element. Hence, the lang attribute must be valid.
```

2023-09-06 14:21 UTC, dan-tripp-siteimprove approved these changes

2023-09-07 13:13 UTC, colabottles approved these changes

2023-09-15 07:44 UTC, WilcoFiers approved these changes

2023-09-15 08:21 UTC, carlosapaduarte approved these changes

2023-09-15 11:58 UTC, giacomo-petri commented
This PR is in call for review for 1 week. Review ends Sept 22nd.

2023-09-26 09:51 UTC, carlosapaduarte commented
Call for review ended: merging

2023-09-26 09:51 UTC, merged