Stop linking to proposed rules
auto-wcag/auto-wcag pull request #2108
Opened 2023-08-31 15:14 UTC by WilcoFiers

Since we have redirects set up now, if the rule isn't approved yet, we don't need to link to proposed rules anymore.

Need for Call for Review: none, editorial stuff

---

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

2023-09-15 07:42 UTC, Jym77 approved these changes

2023-09-15 07:44 UTC, carlosapaduarte requested changes
Some trailing slashes left behind

2023-09-15 07:44 UTC, carlosapaduarte commented on _rules/bypass-blocks-cf77f2.md
> +[block collapsible]: https://www.w3.org/WAI/standards-guidelines/act/rules/3e12e1// 'Rule Block of Repeated Content is Collapsible'
```suggestion
[block collapsible]: https://www.w3.org/WAI/standards-guidelines/act/rules/3e12e1/ 'Rule Block of Repeated Content is Collapsible'
```

2023-09-15 07:44 UTC, carlosapaduarte commented on _rules/bypass-blocks-cf77f2.md
> +[document has landmark]: https://www.w3.org/WAI/standards-guidelines/act/rules/b40fd1// 'Rule Document Has a Landmark with Non-Repeated Content'
```suggestion
[document has landmark]: https://www.w3.org/WAI/standards-guidelines/act/rules/b40fd1/ 'Rule Document Has a Landmark with Non-Repeated Content'
```

2023-09-15 07:44 UTC, carlosapaduarte commented on _rules/bypass-blocks-cf77f2.md
> +[document has instrument to main]: https://www.w3.org/WAI/standards-guidelines/act/rules/ye5d6e// 'Rule Document Has an Instrument to Move Focus to Non-Repeated Content'
```suggestion
[document has instrument to main]: https://www.w3.org/WAI/standards-guidelines/act/rules/ye5d6e/ 'Rule Document Has an Instrument to Move Focus to Non-Repeated Content'
```

2023-09-15 07:44 UTC, carlosapaduarte commented on _rules/bypass-blocks-cf77f2.md
> +[document has heading for main]: https://www.w3.org/WAI/standards-guidelines/act/rules/047fe0// 'Rule Document Has Heading for Non-Repeated Content'
```suggestion
[document has heading for main]: https://www.w3.org/WAI/standards-guidelines/act/rules/047fe0/ 'Rule Document Has Heading for Non-Repeated Content'
```

2023-09-15 07:45 UTC, carlosapaduarte approved these changes

2023-10-13 11:30 UTC, daniel-montalvo approved these changes

2023-10-13 13:58 UTC, merged