Update matching-characters.md
auto-wcag/auto-wcag pull request #2144
Opened 2023-12-01 16:14 UTC by kengdoj

replace broken link with existing "whitespace" glossary term

This will require a 2 weeks Call for Review << new rule, or substantial changes affecting a large number of test cases, if in doubt, use this. >>

---

## Pull Request Etiquette

### **When creating PR:**

- [ ] Make sure you're requesting to **pull a branch** (right side) to the `develop` branch (left side).
- [ ] Make sure you do not remove the "How to Review and Approve" section in your pull request description

### **After creating PR:**

- [ ] Add yourself (and co-authors) as "Assignees" for PR.
- [ ] Add label to indicate if it's a `Rule`, `Definition` or `Chore`.
- [ ] [Link the PR to any issue it solves](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). This will be done automatically by [referencing the issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) at the top of this comment in the indicated place.
- [ ] Optionally request feedback from anyone in particular by assigning them as "Reviewers".

### **When merging a PR:**

- [ ] Close any issue that the PR resolves. This will happen automatically upon merging if the PR was correctly linked to the issue, e.g. by referencing the issue at the top of this comment.

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

2023-12-05 14:14 UTC, WilcoFiers approved these changes

2023-12-05 14:14 UTC, tbostic32 approved these changes

2023-12-07 12:40 UTC, Jym77 requested changes, later dismissed

2023-12-07 12:40 UTC, Jym77 commented on pages/glossary/matching-characters.md
> +A sequence of characters is considered to _match_ another if, after removing leading and trailing [whitespace characters][] and replacing remaining occurrences of one or more whitespace characters wi
```suggestion
A sequence of characters is considered to _match_ another if, after removing leading and trailing [whitespace characters][] and replacing remaining occurrences of one or more whitespace characters with a single space, the two sequences of characters are equal character-by-character, ignoring any differences in letter casing.

[whitespace characters]: #whitespace 'Definition of Whitespace'
```
I'm actually surprised that we don't have a test to catch these missing links in definitions 🤔

2023-12-07 14:11 UTC, WilcoFiers commented on pages/glossary/matching-characters.md
> +A sequence of characters is considered to _match_ another if, after removing leading and trailing [whitespace characters][] and replacing remaining occurrences of one or more whitespace characters wi
Feel free to open a PR 😁

2023-12-07 14:25 UTC, Jym77 commented on pages/glossary/matching-characters.md
> +A sequence of characters is considered to _match_ another if, after removing leading and trailing [whitespace characters][] and replacing remaining occurrences of one or more whitespace characters wi
#2146, in the meantime 🤷‍♀️

2023-12-14 09:49 UTC, Jym77 approved these changes

2024-01-12 15:34 UTC, merged