WCAG 2.2 migration
auto-wcag/auto-wcag pull request #2147
Opened 2023-12-07 13:23 UTC by WilcoFiers

Update all relevant references to WCAG 2.2.

Needs a couple thorough reviews, but I don't believe this needs a call for review.

See also: https://github.com/act-rules/act-tools/pull/33

---

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

2023-12-07 14:07 UTC, Jym77 requested changes, later dismissed
Great work!
A couple of typos.

There is also the "Scrollable content can be reached with sequential focus navigation" rule which is using text from WCAG 2.1 in its examples, might as well be updated to WCAG 2.2.

I've spotted several places (more than I've noted) which link to ARIA 1.1. This should probably be taken separately anyway (#2148). (looks like this is now taken care of 😅)

2023-12-07 14:07 UTC, Jym77 commented on _rules/links-identical-name-equivalent-purpose-b20e66.md
>  [presentational roles conflict resolution]: https://www.w3.org/TR/wai-aria-1.1/#conflict_resolution_presentation_none 'Presentational Roles Conflict Resolution'
(unrelated): 
```suggestion
[presentational roles conflict resolution]: https://www.w3.org/TR/wai-aria-1.2/#conflict_resolution_presentation_none 'Presentational Roles Conflict Resolution'
```

2023-12-07 14:07 UTC, Jym77 commented on _rules/text-contrast-afw4f7.md
>  [presentational roles conflict resolution]: https://www.w3.org/TR/wai-aria-1.1/#conflict_resolution_presentation_none 'WAI-ARIA, Presentational Roles Conflict Resolution'
(unrelated)
```suggestion
[presentational roles conflict resolution]: https://www.w3.org/TR/wai-aria-1.2/#conflict_resolution_presentation_none 'WAI-ARIA, Presentational Roles Conflict Resolution'
```

2023-12-07 14:07 UTC, Jym77 commented on _rules/document-has-landmark-with-non-repeated-content-b40fd1.md
> +- [The `main` role](https://www.w3.org/TR/wai-aria-1.2s/#main)
```suggestion
- [The `main` role](https://www.w3.org/TR/wai-aria-1.2/#main)
```

2023-12-07 14:07 UTC, Jym77 commented on _rules/role-attribute-valid-value-674b10.md
> +- [List of DPUB ARIA Roles](https://www.w3.org/TR/dpub-aria-1.2/#role_definitions)
```suggestion
- [List of DPUB ARIA Roles](https://www.w3.org/TR/dpub-aria-1.1/#role_definitions)
```
DPUB ARIA is still at 1.1

2023-12-20 14:17 UTC, carlosapaduarte approved these changes

2024-01-25 13:49 UTC, WilcoFiers commented on _rules/css-restrict-orientation-b33eff.md
> -	- [matrix3d](https://www.w3.org/TR/css-transforms-2/#funcdef-matrix3d)
This gets treated as a code block, which caused tests to fail.

2024-01-25 14:09 UTC, HelenBurge approved these changes

2024-01-25 14:44 UTC, sujisreerama approved these changes

2024-01-25 17:03 UTC, merged