Correct descriptions of failed examples in valid language tag rule
auto-wcag/auto-wcag pull request #2194
Opened 2024-05-28 13:46 UTC by sabernhardt

The first two failed examples do not have a known primary language tag, and the third example could say "three-letter code."

Need for Call for Review:
This will not require a Call for Review: editorial changes (examples section)

---

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

2024-05-28 13:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/act-rules/act-rules.github.io?pullRequest=2194) <br/>All committers have signed the CLA.

2024-05-30 11:03 UTC, Jym77 requested changes
Well spotted 👍 A bit of polishing.

2024-05-30 11:03 UTC, Jym77 commented on _rules/html-page-lang-valid-bf051a.md
> +This `html` element has a `lang` attribute, but it is not a [known primary language tag][].
```suggestion
This `html` element has a `lang` attribute, with no [known primary language tag][].
```
The value of the `lang` attribute is not (and does not need to be) a primary language tag, only the, well, primary tag needs to be.

2024-05-30 11:03 UTC, Jym77 commented on _rules/html-page-lang-valid-bf051a.md
> +This `html` element has a `lang` attribute, but it is not a [known primary language tag][].
```suggestion
This `html` element has a `lang` attribute, with no [known primary language tag][].
```

2024-05-30 12:32 UTC, giacomo-petri approved these changes
Approving with @Jym77's changes.

2024-12-19 17:30 UTC, carlosapaduarte approved these changes
Committing the changes proposed by @Jym77 to try to move this one forward :-)

2024-12-20 08:06 UTC, Jym77 approved these changes

2024-12-20 09:34 UTC, carlosapaduarte commented
Merging.
Editorial changes, no call for review required.

2024-12-20 09:35 UTC, merged