Text is clipped: "link to a full version"
auto-wcag/auto-wcag pull request #2200
Opened 2024-06-28 22:36 UTC by dan-tripp-siteimprove

Closes issue(s):

- closes #2163

Need for Call for Review:
This will require a 1 week Call for Review 

---

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

2024-07-25 13:46 UTC, WilcoFiers commented on _rules/zoom-text-no-overflow-clipping-59br37.md
> +This [text node][] is [horizontally clipped][] using `text-overflow: ellipsis` at a [viewport size][] of 640 by 512. A link to a full version of the poem is also provided.  Strictly speaking, the lin
This seems a little verbose. How about something like this:

```suggestion
This [text node][] is [horizontally clipped][] using `text-overflow: ellipsis` at a [viewport size][] of 640 by 512. This fulfills expectation 1. A link to a full version of the poem is also provided. The link to the full version is not required by this rule, but is necessary to satisfy [success criterion 1.4.4 Resize text][sc144].```

2024-07-25 13:47 UTC, WilcoFiers requested changes
Left a suggestion

2024-08-29 12:09 UTC, WilcoFiers approved these changes

2024-12-19 10:40 UTC, Jym77 reviewed
Looks good. Not formally approving to get the "3 organisations" in.

2024-12-19 17:23 UTC, carlosapaduarte approved these changes

2025-02-13 16:44 UTC, daniel-montalvo approved these changes

2025-02-20 12:57 UTC, Jym77 commented
Call for review ends on February 27th.

2025-02-20 13:42 UTC, colabottles approved these changes

2025-02-27 11:11 UTC, giacomo-petri approved these changes

2025-05-01 13:41 UTC, merged