Non-role input types require an accessible name
auto-wcag/auto-wcag pull request #2228
Opened 2024-11-21 18:06 UTC by WilcoFiers

Noticed this when reviewing the form control rule. I think we need to do the same for the `Form field label is descriptive` rule. Leaving this as a draft PR until then.

Need for Call for Review: 1 week

---

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

2024-12-19 09:45 UTC, Jym77 commented
Closes #2123.

2024-12-19 10:31 UTC, Jym77 requested changes, later dismissed

2024-12-19 10:31 UTC, Jym77 commented on _rules/form-field-non-empty-accessible-name-e086e5.md
> +- the element is an `input` with no [semantic role][] and a `type` [attribute value][] of `color`, `date`, `datetime-local`, `month`, `password`, `time`, or `week`.
```suggestion
- the element is an `input` with no [semantic role][] and a `type` [attribute value][] of `color`, `date`, `datetime-local`, `file`, `month`, `password`, `time`, or `week`.
```

2024-12-19 17:30 UTC, giacomo-petri commented
Already approving. Good catch @Jym77

2024-12-19 17:30 UTC, giacomo-petri approved these changes

2025-02-06 13:17 UTC, carlosapaduarte approved these changes

2025-02-06 14:08 UTC, Jym77 approved these changes
Minor improvement on the background note.

2025-02-06 14:08 UTC, Jym77 commented on _rules/form-field-non-empty-accessible-name-e086e5.md
> +This rule does not test other control-like roles such as `button` and `menuitem`, because these do not inherit from `input` or `select`. These should be tested separately. Because certain input types
```suggestion
This rule does not test other control-like roles such as `button` and `menuitem`, because these do not inherit from `input` or `select`; these should be tested separately. This rule does test certain specific input types such as date and color because they have no semantic role, but still require an accessible name.
```

2026-01-08 13:05 UTC, Jym77 commented
Call for Review ends on January 15th.

2026-01-23 14:19 UTC, Jym77 commented
Call for Reviews has ended. Merging.

2026-01-23 14:19 UTC, merged