Editorial update iframe focusable
auto-wcag/auto-wcag pull request #2229
Opened 2024-12-05 11:06 UTC by WilcoFiers

This seemed slightly better to me.

Need for Call for Review: None, editorial

---

## How to Review And Approve

- Go to the “Files changed” tab
- Here you will have the option to leave comments on different lines.
- Once the review is completed, find the “Review changes” button in the top right, select “Approve” (if you are really confident in the rule) or "Request changes" and click “Submit review”.
- Make sure to also review the proposed Call for Review period. In case of disagreement, the longer period wins.

2024-12-19 09:36 UTC, Jym77 requested changes, later dismissed
Isn't that a case where Scenario 1 (the rule is not as strict as a requirement) of [Secondary requirements](https://w3c.github.io/wcag-act/act-rules-format.html#secondary-requirements) applies?

That is, anything that fails 2.1.1 also automatically fails 2.1.3, similarly to the 1.4.3/1.4.6 situation. 

Additionally, 2.1.3 is a AAA criterion, so having this as a primary requirements means that tools that only check for level AA will never be able to have a consistent implementation of the rule (which was pretty much what led us to introduce secondary requirements for the 1.4.3/1.4.6 or 2.4.6/2.4.9 cases: [initial PR](https://github.com/act-rules/act-rules.github.io/pull/1920), linking to more issues in the wcag-act-rules repo)

2025-01-16 13:46 UTC, WilcoFiers commented
@Jym77 
1. While yes, criterion 2.1.3 is stricter then criterion 2.1.1, 2.1.3 isn't stricter then this rule. There are no passed examples that fail 2.1.3 but don't fail 2.1.1 like is the case for text contrast. That's essentially the difference between a conformance requirement and a secondary requirement. A secondary requirement may fail passed exampled (stricter) or it may pass failed examples (less strict), or in a few cases it can do both. When all failed examples fail a criterion, and all passed / inapplicable examples meet the requirement it's a conformance requirement, not a secondary requirement.

2. ACT allows implementations to be consistent at lower levels. I.e. you're only required to report AAA criteria if you test for AAA. The way we check that is by checking if any AAA criteria are reported. So you can't do AAA for some rules but not for others. There is an open bug in how this works though, so this isn't working correctly everywhere.

2025-01-16 13:57 UTC, Jym77 approved these changes

2025-02-06 12:00 UTC, carlosapaduarte approved these changes

2025-04-10 13:09 UTC, giacomo-petri approved these changes

2025-04-10 16:58 UTC, shunguoy commented
@WilcoFiers  another [issue related to this rule](https://github.com/act-rules/act-rules.github.io/issues/2320).

2025-05-01 13:40 UTC, WilcoFiers commented
I forgot to put the call for review label on this, but that e-mail went out on April 10th. That's over two weeks ago, so I'm merging this PR.

2025-05-01 13:40 UTC, merged